name: CI
on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  validate:
    name: validate
    runs-on: ubuntu-latest
    steps:
      - name: Setup go 1.14
        uses: actions/setup-go@v2
        with: {go-version: '1.14'}
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Install artifactvalidator
        run: go get github.com/forensicanalysis/artifactlib/cmd/artifactvalidator
      - name: Validate artifacts
        run: artifactvalidator -s *.yaml
