name: CI
on: [push]

jobs:

  validate:
    name: artifactcollector
    runs-on: ubuntu-latest
    steps:
      - name: Setup go 1.13
        uses: actions/setup-go@v1
        with: {go-version: '1.13'}
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Set system path
        run: echo "##[add-path]$(go env GOPATH)/bin"
      - name: Install artifactvalidator
        run: go get github.com/forensicanalysis/artifactlib/cmd/artifactvalidator
      - name: Validate artifacts
        run: artifactvalidator *.yaml
